### PR TITLE
New output formats for Bins

### PR DESCRIPTION
**Pull request by Paebbels**
And here comes PR number 2.

This is my current implementation state for CSV and JSON output. Please comment on my proposed changes.

P.S. I'm investigating, if it's possible to implement a JSON parser and writer in a protected type.

### CODE REVIEW

**Comment by tmeissner** [comment]
I've implemented XML export for the WriteBin procedure in our internal development branch of OSVVM. Maybe we can merge these 3 output formats. My code isn't so beautiful at the moment, I've to clean it up before.

**Comment by Paebbels** [comment]
Hello Torsten,

yes, this PR is still open, but I think I'll all of it and create a new one.

I had a discussion with Jim, and I think a good solution is to implement each format in a separate protected type. Allowing XML output was also a point for a future release.

Such formatter objects could than be selected and used to write bins to the disk.

Regards
    Patrick

**Comment by tmeissner** [comment]
Okay, in the meantime we use our self implemented XML export. Maybe I can talk with Jim about this if the OSVVM course at PLC2 takes place at beginning of may.

**Comment by Paebbels** [comment]
As this PR got incompatible due to OSVVM changes, I'll close this PR.

The proposed changes have been moved to repository: [PLC2/OSVVM](https://github.com/PLC2/OSVVM) on branch `paebbels/csv`.

If needed, please create a new PR.

**Pull request closed without merging**
